const dummyData = {
  colleges: [
    {
      id: 1,
      name: "Elysium College",
      course: "Computer Science",
      fees: 15000,
      user_rating: 4.2,
      ranking: 25,
    },
    {
      id: 2,
      name: "Olympus University",
      course: "Engineering",
      fees: 18000,
      user_rating: 4.5,
      ranking: 12,
    },
    {
      id: 3,
      name: "Zenith Institute",
      course: "Business Administration",
      fees: 20000,
      user_rating: 4.1,
      ranking: 18,
    },
    {
      id: 4,
      name: "Aurora College",
      course: "Medicine",
      fees: 25000,
      user_rating: 4.7,
      ranking: 8,
    },
    {
      id: 5,
      name: "Vertex University",
      course: "Law",
      fees: 22000,
      user_rating: 4.3,
      ranking: 15,
    },
    {
      id: 6,
      name: "Nebula College",
      course: "Physics",
      fees: 17000,
      user_rating: 4.0,
      ranking: 21,
    },
    {
      id: 7,
      name: "Horizon Institute",
      course: "Psychology",
      fees: 19000,
      user_rating: 4.4,
      ranking: 17,
    },
    {
      id: 8,
      name: "Pinnacle University",
      course: "Economics",
      fees: 21000,
      user_rating: 4.6,
      ranking: 9,
    },
    {
      id: 9,
      name: "Cascade College",
      course: "Chemistry",
      fees: 16000,
      user_rating: 3.9,
      ranking: 29,
    },
    {
      id: 10,
      name: "Apex Institute",
      course: "Political Science",
      fees: 23000,
      user_rating: 4.8,
      ranking: 5,
    },
    {
      id: 11,
      name: "Summit University",
      course: "Mathematics",
      fees: 24000,
      user_rating: 4.2,
      ranking: 13,
    },
    {
      id: 12,
      name: "Acme College",
      course: "Fine Arts",
      fees: 20000,
      user_rating: 4.0,
      ranking: 20,
    },
    {
      id: 13,
      name: "Alpha Institute",
      course: "Literature",
      fees: 18000,
      user_rating: 4.5,
      ranking: 11,
    },
    {
      id: 14,
      name: "Omega University",
      course: "History",
      fees: 21000,
      user_rating: 4.3,
      ranking: 16,
    },
    {
      id: 15,
      name: "Titan College",
      course: "Sociology",
      fees: 17000,
      user_rating: 4.1,
      ranking: 22,
    },
    {
      id: 16,
      name: "Galaxy Institute",
      course: "Environmental Science",
      fees: 19000,
      user_rating: 4.6,
      ranking: 10,
    },
    {
      id: 17,
      name: "Stellar University",
      course: "Astrophysics",
      fees: 22000,
      user_rating: 4.7,
      ranking: 7,
    },
    {
      id: 18,
      name: "Cosmos College",
      course: "Biology",
      fees: 20000,
      user_rating: 4.4,
      ranking: 14,
    },
    {
      id: 19,
      name: "Celestial Institute",
      course: "Geology",
      fees: 23000,
      user_rating: 4.2,
      ranking: 19,
    },
    {
      id: 20,
      name: "Orion University",
      course: "Astronomy",
      fees: 25000,
      user_rating: 4.8,
      ranking: 6,
    },
    {
      id: 21,
      name: "Nebula College",
      course: "Meteorology",
      fees: 18000,
      user_rating: 4.0,
      ranking: 24,
    },
    {
      id: 22,
      name: "Polaris Institute",
      course: "Oceanography",
      fees: 21000,
      user_rating: 4.5,
      ranking: 12,
    },
    {
      id: 23,
      name: "Astralis University",
      course: "Marine Biology",
      fees: 24000,
      user_rating: 4.3,
      ranking: 9,
    },
    {
      id: 24,
      name: "Spectrum College",
      course: "Zoology",
      fees: 20000,
      user_rating: 4.6,
      ranking: 15,
    },
    {
      id: 25,
      name: "Equinox Institute",
      course: "Botany",
      fees: 17000,
      user_rating: 4.1,
      ranking: 23,
    },
    {
      id: 26,
      name: "Altair University",
      course: "Ecology",
      fees: 19000,
      user_rating: 4.7,
      ranking: 8,
    },
    {
      id: 27,
      name: "Nova College",
      course: "Conservation Biology",
      fees: 22000,
      user_rating: 4.4,
      ranking: 13,
    },
    {
      id: 28,
      name: "Radiant Institute",
      course: "Genetics",
      fees: 20000,
      user_rating: 4.2,
      ranking: 18,
    },
    {
      id: 29,
      name: "Luminous University",
      course: "Biochemistry",
      fees: 23000,
      user_rating: 4.9,
      ranking: 4,
    },
    {
      id: 30,
      name: "Solaris College",
      course: "Microbiology",
      fees: 25000,
      user_rating: 4.3,
      ranking: 11,
    },
    {
      id: 31,
      name: "Zephyr Institute",
      course: "Immunology",
      fees: 18000,
      user_rating: 4.7,
      ranking: 7,
    },
    {
      id: 32,
      name: "Borealis University",
      course: "Pharmacology",
      fees: 21000,
      user_rating: 4.5,
      ranking: 10,
    },
    {
      id: 33,
      name: "Glow College",
      course: "Toxicology",
      fees: 19000,
      user_rating: 4.1,
      ranking: 16,
    },
    {
      id: 34,
      name: "Flare Institute",
      course: "Pathology",
      fees: 22000,
      user_rating: 4.6,
      ranking: 9,
    },
    {
      id: 35,
      name: "Blaze University",
      course: "Neuroscience",
      fees: 20000,
      user_rating: 4.4,
      ranking: 14,
    },
    {
      id: 36,
      name: "Radiant College",
      course: "Physiology",
      fees: 23000,
      user_rating: 4.8,
      ranking: 5,
    },
    {
      id: 37,
      name: "Shine Institute",
      course: "Anatomy",
      fees: 25000,
      user_rating: 4.2,
      ranking: 19,
    },
    {
      id: 38,
      name: "Dawn University",
      course: "Biophysics",
      fees: 17000,
      user_rating: 4.9,
      ranking: 3,
    },
    {
      id: 39,
      name: "Twilight College",
      course: "Bioinformatics",
      fees: 19000,
      user_rating: 4.3,
      ranking: 17,
    },
    {
      id: 40,
      name: "Sunrise Institute",
      course: "Ecology",
      fees: 22000,
      user_rating: 4.7,
      ranking: 6,
    },
    {
      id: 41,
      name: "Sunset University",
      course: "Biotechnology",
      fees: 20000,
      user_rating: 4.5,
      ranking: 12,
    },
    {
      id: 42,
      name: "Moonlight College",
      course: "Cell Biology",
      fees: 24000,
      user_rating: 4.1,
      ranking: 20,
    },
    {
      id: 43,
      name: "Stardust Institute",
      course: "Molecular Biology",
      fees: 21000,
      user_rating: 4.8,
      ranking: 4,
    },
    {
      id: 44,
      name: "Comet University",
      course: "Bioengineering",
      fees: 23000,
      user_rating: 4.6,
      ranking: 10,
    },
    {
      id: 45,
      name: "Meteor College",
      course: "Genomics",
      fees: 20000,
      user_rating: 4.2,
      ranking: 16,
    },
    {
      id: 46,
      name: "Asteroid Institute",
      course: "Immunogenetics",
      fees: 25000,
      user_rating: 4.9,
      ranking: 2,
    },
    {
      id: 47,
      name: "Galactic University",
      course: "Bioethics",
      fees: 18000,
      user_rating: 4.4,
      ranking: 15,
    },
    {
      id: 48,
      name: "Supernova Institute",
      course: "Biochemical Engineering",
      fees: 22000,
      user_rating: 4.7,
      ranking: 7,
    },
    {
      id: 49,
      name: "Quasar College",
      course: "Systems Biology",
      fees: 19000,
      user_rating: 4.3,
      ranking: 13,
    },
    {
      id: 50,
      name: "Nucleus University",
      course: "Computational Biology",
      fees: 24000,
      user_rating: 4.8,
      ranking: 5,
    },
    {
      id: 51,
      name: "Starlight College",
      course: "Astrobiology",
      fees: 23000,
      user_rating: 4.6,
      ranking: 11,
    },
    {
      id: 52,
      name: "Cosmic Institute",
      course: "Astrochemistry",
      fees: 22000,
      user_rating: 4.5,
      ranking: 14,
    },
    {
      id: 53,
      name: "Supernova University",
      course: "Astrogeology",
      fees: 21000,
      user_rating: 4.7,
      ranking: 8,
    },
    {
      id: 54,
      name: "Quasar Institute",
      course: "Astronautics",
      fees: 20000,
      user_rating: 4.4,
      ranking: 17,
    },
    {
      id: 55,
      name: "Star Institute",
      course: "Astrophotography",
      fees: 24000,
      user_rating: 4.8,
      ranking: 4,
    },
    {
      id: 56,
      name: "Orbit College",
      course: "Astroinformatics",
      fees: 25000,
      user_rating: 4.3,
      ranking: 10,
    },
    {
      id: 57,
      name: "Galaxy University",
      course: "Astrophysics",
      fees: 23000,
      user_rating: 4.9,
      ranking: 2,
    },
    {
      id: 58,
      name: "Comet College",
      course: "Astrodynamics",
      fees: 22000,
      user_rating: 4.6,
      ranking: 7,
    },
    {
      id: 59,
      name: "Nebula Institute",
      course: "Astrobiology",
      fees: 21000,
      user_rating: 4.4,
      ranking: 13,
    },
    {
      id: 60,
      name: "Solar Institute",
      course: "Astronautical Engineering",
      fees: 19000,
      user_rating: 4.7,
      ranking: 9,
    },
    {
      id: 61,
      name: "Galactic College",
      course: "Astrogeophysics",
      fees: 18000,
      user_rating: 4.5,
      ranking: 15,
    },
    {
      id: 62,
      name: "Celestial University",
      course: "Astrochemistry",
      fees: 17000,
      user_rating: 4.2,
      ranking: 20,
    },
    {
      id: 63,
      name: "Starlight College",
      course: "Astrobiology",
      fees: 24000,
      user_rating: 4.8,
      ranking: 3,
    },
    {
      id: 64,
      name: "Cosmic Institute",
      course: "Astrogeology",
      fees: 23000,
      user_rating: 4.6,
      ranking: 6,
    },
    {
      id: 65,
      name: "Supernova University",
      course: "Astrophotography",
      fees: 22000,
      user_rating: 4.3,
      ranking: 11,
    },
    {
      id: 66,
      name: "Quasar Institute",
      course: "Astroinformatics",
      fees: 21000,
      user_rating: 4.9,
      ranking: 5,
    },
    {
      id: 67,
      name: "Star Institute",
      course: "Astrodynamics",
      fees: 20000,
      user_rating: 4.7,
      ranking: 12,
    },
    {
      id: 68,
      name: "Orbit College",
      course: "Astronomy",
      fees: 19000,
      user_rating: 4.4,
      ranking: 16,
    },
    {
      id: 69,
      name: "Galaxy University",
      course: "Astrophysics",
      fees: 18000,
      user_rating: 4.2,
      ranking: 19,
    },
    {
      id: 70,
      name: "Comet College",
      course: "Astrobiology",
      fees: 17000,
      user_rating: 4.8,
      ranking: 4,
    },
    {
      id: 71,
      name: "Nebula Institute",
      course: "Astrogeophysics",
      fees: 24000,
      user_rating: 4.6,
      ranking: 8,
    },
    {
      id: 72,
      name: "Solar Institute",
      course: "Astrochemistry",
      fees: 23000,
      user_rating: 4.3,
      ranking: 10,
    },
    {
      id: 73,
      name: "Galactic College",
      course: "Astronomical Engineering",
      fees: 22000,
      user_rating: 4.9,
      ranking: 2,
    },
    {
      id: 74,
      name: "Celestial University",
      course: "Astrogeology",
      fees: 20000,
      user_rating: 4.7,
      ranking: 7,
    },
    {
      id: 75,
      name: "Starlight College",
      course: "Astrophotography",
      fees: 19000,
      user_rating: 4.4,
      ranking: 13,
    },
    {
      id: 76,
      name: "Cosmic Institute",
      course: "Astroinformatics",
      fees: 18000,
      user_rating: 4.2,
      ranking: 17,
    },
    {
      id: 77,
      name: "Supernova University",
      course: "Astrodynamics",
      fees: 17000,
      user_rating: 4.8,
      ranking: 5,
    },
    {
      id: 78,
      name: "Quasar Institute",
      course: "Astronomy",
      fees: 24000,
      user_rating: 4.6,
      ranking: 9,
    },
    {
      id: 79,
      name: "Star Institute",
      course: "Astrophysics",
      fees: 23000,
      user_rating: 4.3,
      ranking: 11,
    },
    {
      id: 80,
      name: "Orbit College",
      course: "Astrobiology",
      fees: 22000,
      user_rating: 4.9,
      ranking: 3,
    },
    {
      id: 81,
      name: "Galaxy University",
      course: "Astrogeophysics",
      fees: 20000,
      user_rating: 4.7,
      ranking: 6,
    },
    {
      id: 82,
      name: "Comet College",
      course: "Astrochemistry",
      fees: 19000,
      user_rating: 4.4,
      ranking: 14,
    },
    {
      id: 83,
      name: "Nebula Institute",
      course: "Astroinformatics",
      fees: 18000,
      user_rating: 4.2,
      ranking: 18,
    },
    {
      id: 84,
      name: "Solar Institute",
      course: "Astrodynamics",
      fees: 17000,
      user_rating: 4.8,
      ranking: 4,
    },
    {
      id: 85,
      name: "Galactic College",
      course: "Astronomy",
      fees: 24000,
      user_rating: 4.6,
      ranking: 7,
    },
    {
      id: 86,
      name: "Celestial University",
      course: "Astrophysics",
      fees: 23000,
      user_rating: 4.3,
      ranking: 10,
    },
    {
      id: 87,
      name: "Starlight College",
      course: "Astrogeophysics",
      fees: 22000,
      user_rating: 4.9,
      ranking: 2,
    },
    {
      id: 88,
      name: "Cosmic Institute",
      course: "Astrochemistry",
      fees: 20000,
      user_rating: 4.7,
      ranking: 8,
    },
    {
      id: 89,
      name: "Supernova University",
      course: "Astrogeology",
      fees: 19000,
      user_rating: 4.4,
      ranking: 12,
    },
    {
      id: 90,
      name: "Quasar Institute",
      course: "Astronautics",
      fees: 18000,
      user_rating: 4.2,
      ranking: 15,
    },
    {
      id: 91,
      name: "Star Institute",
      course: "Astrophotography",
      fees: 17000,
      user_rating: 4.8,
      ranking: 3,
    },
    {
      id: 92,
      name: "Orbit College",
      course: "Astroinformatics",
      fees: 24000,
      user_rating: 4.6,
      ranking: 6,
    },
    {
      id: 93,
      name: "Galaxy University",
      course: "Astrodynamics",
      fees: 23000,
      user_rating: 4.3,
      ranking: 11,
    },
    {
      id: 94,
      name: "Comet College",
      course: "Astronomy",
      fees: 22000,
      user_rating: 4.9,
      ranking: 2,
    },
    {
      id: 95,
      name: "Nebula Institute",
      course: "Astrobiology",
      fees: 20000,
      user_rating: 4.7,
      ranking: 8,
    },
    {
      id: 96,
      name: "Solar Institute",
      course: "Astrogeophysics",
      fees: 19000,
      user_rating: 4.4,
      ranking: 12,
    },
    {
      id: 97,
      name: "Galactic College",
      course: "Astrochemistry",
      fees: 18000,
      user_rating: 4.2,
      ranking: 16,
    },
    {
      id: 98,
      name: "Celestial University",
      course: "Astrophysics",
      fees: 17000,
      user_rating: 4.8,
      ranking: 4,
    },
    {
      id: 99,
      name: "Starlight College",
      course: "Astrogeophysics",
      fees: 24000,
      user_rating: 4.6,
      ranking: 7,
    },
    {
      id: 100,
      name: "Cosmic Institute",
      course: "Astronomy",
      fees: 23000,
      user_rating: 4.3,
      ranking: 11,
    },
  ],
};

export default dummyData;
